Feature/saving ideas in concept
openstad/openstad-api pull request #252
Opened 2022-09-29 14:54 UTC by LorenzoJokhan

# Description
Added migration to add publishedDate field to the ideas table
Added migration to update all old plans with a publishedField value equal to their creation date
Changed onlyVisible to only return ideas that are in concept when created by yourself or if you are an admin.

Please include
Is a dependency of https://github.com/openstad/openstad-frontend/pull/359

2022-10-04 11:57 UTC, nlsvgtr requested changes
I think it's ok like this. I added one comment where I am not sure, please double check.

One request: if it's all the same to you could you rename publishedDate to publishDate? That would give us the option to add extra functionality later: if you would use dates in the future you could write something now that would be automatically be published later.

2022-10-04 11:57 UTC, nlsvgtr commented on src/models/Idea.js
> +                  publishedDate: {[Op.ne]: null}
I could be reading this wrong, but I think this means that an Idea that has viewableByRole set to admin is now viewable by other users when the published date is null.

2022-10-04 11:57 UTC, nlsvgtr commented on src/models/Idea.js
> +                  publishedDate: {[Op.ne]: null}
But maybe it works correctly because Sequelize defaults this to an AND statement?

2022-10-04 14:41 UTC, LorenzoJokhan commented on src/models/Idea.js
> +                  publishedDate: {[Op.ne]: null}
Sequealize creates an AND statement between each array of [Op.or]. When you are not logged in than you will only receive the published ideas that you are allowed to view, this is the query that is generated for when the user is logged in:

SELECT
    `idea`.`id`,
    `idea`.`siteId`,
    `idea`.`userId`,
    `idea`.`startDate`,
    `idea`.`sort`,
    `idea`.`typeId`,
    `idea`.`status`,
    `idea`.`viewableByRole`,
    `idea`.`title`,
    `idea`.`summary`,
    `idea`.`description`,
    `idea`.`budget`,
    `idea`.`extraData`,
    `idea`.`location`,
    `idea`.`modBreak`,
    `idea`.`modBreakUserId`,
    `idea`.`modBreakDate`,
    `idea`.`publishedDate`,
    `idea`.`createdAt`,
    `idea`.`updatedAt`,
    `idea`.`deletedAt`,
    (
        SELECT
            COUNT(*)
        FROM
            votes v
        WHERE
            v.deletedAt IS NULL
            AND (
                v.checked IS NULL
                OR v.checked = 1
            )
            AND v.ideaId = idea.id
            AND v.opinion = "yes"
    ) AS `yes`,
    (
        SELECT
            COUNT(*)
        FROM
            votes v
        WHERE
            v.deletedAt IS NULL
            AND (
                v.checked IS NULL
                OR v.checked = 1
            )
            AND v.ideaId = idea.id
            AND v.opinion = "no"
    ) AS `no`,
    (
        SELECT
            COUNT(*)
        FROM
            arguments a
        WHERE
            a.deletedAt IS NULL
            AND a.ideaId = idea.id
    ) AS `argCount`,
    `tags`.`id` AS `tags.id`,
    `tags`.`name` AS `tags.name`
FROM
    `ideas` AS `idea`
    LEFT OUTER JOIN (
        `ideaTags` AS `tags->ideaTags`
        INNER JOIN `tags` AS `tags` ON `tags`.`id` = `tags->ideaTags`.`tagId`
    ) ON `idea`.`id` = `tags->ideaTags`.`ideaId`
    AND (`tags`.`deletedAt` IS NULL)
WHERE
    (
        `idea`.`deletedAt` IS NULL
        AND (
            (
                `idea`.`viewableByRole` = 'all'
                OR `idea`.`viewableByRole` IS NULL
                OR `idea`.`viewableByRole` = ''
            )
            AND NOT (`idea`.`publishedDate` IS NULL)
            AND `idea`.`siteId` = '3'
        )
    )
ORDER BY
    `idea`.`createdAt` DESC;

2022-10-04 14:50 UTC, LorenzoJokhan commented
Changed all ocurences of publishedDate to publishDate, will test tomorrow if everything still works and will give a sign if everything is ok

2022-10-04 15:03 UTC, rudivanhierden requested changes

2022-10-04 15:03 UTC, rudivanhierden commented on src/models/Idea.js
> +        var date = this.getDataValue('publishDate');
```suggestion
        const date = this.getDataValue('publishDate');
```

2022-10-04 15:03 UTC, rudivanhierden commented on src/routes/api/idea.js
> +    }
This code is now duplicated in this file, can you extract it to a middleware?

2022-10-05 07:16 UTC, LorenzoJokhan commented on migrations/036-prefill-existing-plans-published-date.js
> +				WHERE createdAt < '2022-09-30'
That is true, i will remove the where

2022-10-05 07:44 UTC, rudivanhierden approved these changes
Thanks for the changes, LGTM! 🚀

2022-10-05 07:47 UTC, LorenzoJokhan commented on src/models/Idea.js
> +                  publishedDate: {[Op.ne]: null}
Everything works as expected

2022-10-05 07:49 UTC, merged