Rework classes to anonymize users in the background
openstad/openstad-api pull request #292
Opened 2023-03-06 08:57 UTC by LorenzoJokhan

2023-03-06 12:57 UTC, nlsvgtr requested changes

2023-03-06 12:57 UTC, nlsvgtr commented on src/models/Site.js
> +      console.log({result});
Een verdwaalde console.log

2023-03-06 12:57 UTC, nlsvgtr commented on src/models/Site.js
> +          let which = req.query.useOauth || 'default';
req.query heb je hier niet. Net zo min als req.site en req.params hieronder.

2023-03-06 12:57 UTC, nlsvgtr commented on src/models/Site.js
> +          let which = req.query.useOauth || 'default';
Wat is overigens de reden dat je dat nar hier hebt verplaatst? Ik vermoed omdat het in principe netter is om het in het model te doen, maar de reden om het niet hier te doen was dat je nu de instantie Site=12 verantwoordelijk maakt voor users die niet onder site 12 vallen. 
Voor beide valt wat te zeggen denk ik....

2023-03-06 12:57 UTC, nlsvgtr commented on src/models/Site.js
> -      result = await self.willAnonymizeAllUsers();
Om mijn nieuwsgierigheid te bevredigen: waarom heb je dit weggehaald en er functieparams van gemaakt?

2023-03-06 12:57 UTC, nlsvgtr commented on src/models/Site.js
> +          let which = req.query.useOauth || 'default';
Oh, ik zie nu dat je de req meestuurt. Zou je daar losse params van kunnen maken? req is een concept dat niet in een model thuis hoort denk ik.

2023-03-06 13:07 UTC, LorenzoJokhan commented on src/models/Site.js
> -      result = await self.willAnonymizeAllUsers();
Dit heb ik gedaan bij site.js regel 292 tot 295, omdat in beiden cases willAnonymizeAllUsers wordt aangeroepen. Verder werdt de methode willAnonymizeAllUsers slechts in site.js gebruikt. Daarnaast als je ooit een andere groep gebruikers zou willen anonimiseren of een subset daarvan dan hoef je alleen maar een andere array door te geven aan doAnonymizeAllUsers. Dat waren over het algemeen mijn beredenaties

2023-03-07 11:19 UTC, nlsvgtr approved these changes

2023-03-07 11:25 UTC, nlsvgtr commented
Dit lijkt me prima zo.

Heb ik wel een vervolg verzoek: kun je kijken of er iets van feedback mogelijk is.

De netste oplossing zou zijn om eea via actions te laten werken, maar voor nu misschien een beetje overkill.

Voor het genereren van unieke ccodes gebeurd dat in de oauth server. Die heeft wat extra routes om de status van het genereren op te vragen. Nu is dat geen ideale oplossing, maar kijk er eens naar en misschien kun je wat leuks bedenken...

2023-03-07 11:52 UTC, merged